Ignore rules other than `string` rules or `Rule` objects
knuckleswtf/scribe pull request #219
Opened 2021-05-24 11:07 UTC by andronikigr

This Pull Request will resolve the issue here: https://github.com/knuckleswtf/scribe/issues/212

@shalvah 
I follow the suggestions you made in your answer to my question.

2021-05-24 14:57 UTC, shalvah requested changes

2021-05-24 14:57 UTC, shalvah commented on src/Extracting/Strategies/BodyParameters/GetFromFormRequest.php
> +            if (!is_string($ruleset) && !($ruleset instanceof Rule)) continue;
Did you test this? I think the `ruleset` here is actually the group of all rules, which should be an array. I believe this should go in `parseRule()`, the function that parses each rule individually. Even better, this method (where therre's already a check for `Rule` class):

https://github.com/knuckleswtf/scribe/blob/73351b170450d69e4039edd58034a883d4b0648e/src/Extracting/Strategies/BodyParameters/GetFromFormRequest.php#L399-L409

2021-06-05 01:51 UTC, WesleyGoncalves commented
The PR changes worked for me.

2021-06-08 09:02 UTC, shalvah commented
> It actually worked for the first time I executed the script. Second time, it stops with this error
> 
> > rmdir(/path/to/project_dir/public/vendor/scribe/images): Directory not empty

That's an unrelated error; should have been fixed in recent versions.

2021-06-08 09:19 UTC, shalvah commented
> The PR changes worked for me.

Also, yes, the PR changes will work for you in the sense that Scribe won't crash, but _all_ your validation rules will be ignored. You can check and confirm that.

Closing this PR for the real fix.

2021-06-08 09:19 UTC, closed without merging