Allow config and temp directories to be configured independently.
knuckleswtf/scribe pull request #760
Opened 2023-11-07 00:42 UTC by ArclightHub

### Whats changed?

- **Added** the ability to configure the `scribe.php` (or custom php config file) independently of the temp directory.
- **Added** a `docker-compose` setup to allow others to quickly run the test suite on their local machines without needing to install the test stack onto their environment.

### How do I run the tests in the new docker container?
- Simply run `clear && docker-compose up -d && docker logs -f scribe_app_1` and the tests are run and results printed into your terminal!

2023-11-19 01:00 UTC, shalvah commented on src/Extracting/ApiDetails.php
> +    public function __construct(DocumentationConfig $config = null, bool $preserveUserChanges = true, CacheConfiguration $docsName)
Can you fix this?

2023-11-19 01:10 UTC, shalvah requested changes
I like the goal here, but I think the API can be improved. I thnk there are quite a few naming mismatches, which make it harder to follow (`$configObject` implies this is the general Scribe config, but it's a very limited subset of the configuration; `scribeConfig` implies a config object, but it's a file, etc). Additionally, lines like `new CacheConfiguration($configName, $configName, true)` are not very expressive.

2023-11-19 01:10 UTC, shalvah commented on src/GroupedEndpoints/GroupedEndpointsFactory.php
> +        CacheConfiguration $docsName
This seems like mismatching parameter names? Name `$docsName` and type `CacheConfiguration` (also in the other places in this file)
```

2023-11-19 01:10 UTC, shalvah commented on src/Writing/Writer.php
> +                $collectionPath = Storage::disk('local')->path($this->docsName->getScribeConfigFile() . "/collection.json");
If we're doing this, perhaps we should move away from concatenation, and just make it a resolver (a la Laravel's `storage_path(...)`)? Somethig like:

```php
Storage::disk('local')->path($this->paths->outputFile("/collection.json"));
```

2023-11-26 23:12 UTC, ArclightHub commented
I will split this into two separate PRs

2023-11-26 23:12 UTC, closed without merging